language: cpp
git:
  depth: 1
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-6
before_script:
  - export CXX=g++-6
script:
  - mkdir build && cd build
  - cmake ..
  - make VERBOSE=1
